# Generated by Django 5.0.1 on 2025-10-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigScreenAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='大屏与对应实体关联的唯一标识', max_length=50, verbose_name='关联key')),
                ('name', models.CharField(blank=True, max_length=256, null=True, verbose_name='关联名称')),
                ('bigscreen_url', models.CharField(blank=True, max_length=256, null=True, verbose_name='对应大屏地址')),
                ('param', models.CharField(blank=True, max_length=100, null=True, verbose_name='参数')),
            ],
        ),
        migrations.CreateModel(
            name='CustomBigScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='大屏名称')),
                ('ispublished', models.BooleanField(verbose_name='是否发布')),
                ('config', models.TextField(blank=True, null=True, verbose_name='配置内容')),
                ('lists', models.TextField(blank=True, null=True, verbose_name='模板参数内容')),
                ('thumbnail', models.TextField(blank=True, null=True, verbose_name='缩略图')),
                ('modified_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='修改人')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人')),
                ('creat_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '自定义大屏',
                'verbose_name_plural': '自定义大屏',
                'db_table': 'monitor_custom_bigscreen',
            },
        ),
        migrations.CreateModel(
            name='CustomBigScreenBusCom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='业务组件名称')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='标题')),
                ('child', models.TextField(blank=True, null=True, verbose_name='子级内容')),
                ('component', models.TextField(blank=True, null=True, verbose_name='组件内容')),
                ('thumbnail', models.TextField(blank=True, null=True, verbose_name='缩略图')),
                ('dataFormatter', models.TextField(blank=True, null=True, verbose_name='数据格式化函数')),
                ('formatter', models.TextField(blank=True, null=True, verbose_name='格式化函数')),
                ('dataMethod', models.CharField(blank=True, max_length=50, null=True, verbose_name='请求方法')),
                ('url', models.CharField(blank=True, max_length=2048, null=True, verbose_name='URL')),
                ('time', models.IntegerField(blank=True, help_text='左边距', null=True, verbose_name='刷新时间')),
                ('data', models.TextField(blank=True, null=True, verbose_name='数据')),
                ('helpText', models.CharField(blank=True, max_length=255, null=True, verbose_name='提示文本')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='图标类名')),
                ('index', models.IntegerField(blank=True, help_text='组件顺序', null=True, verbose_name='组件顺序')),
                ('zIndex', models.IntegerField(blank=True, help_text='样式层级', null=True, verbose_name='样式层级')),
                ('dataType', models.IntegerField(blank=True, help_text='数据类型', null=True, verbose_name='数据类型')),
                ('modified_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='修改人')),
                ('creator', models.CharField(blank=True, max_length=20, null=True, verbose_name='创建人')),
                ('creat_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '业务组件',
                'verbose_name_plural': '业务组件',
                'db_table': 'monitor_custom_bigscreen_bus_com',
            },
        ),
    ]
